using System;
using System.Reflection;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace SharpSync.Core.Generators
{
    public class HookGenerator
    {
        private readonly HashSet<Type> _zodEnabledTypes;

        public HookGenerator(HashSet<Type> zodEnabledTypes)
        {
            _zodEnabledTypes = zodEnabledTypes;
        }

        public string GenerateHookFile(Type controllerType, DependencyResolver resolver, FrameworkType framework = FrameworkType.React)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SharpSync");
            
            switch (framework)
            {
                case FrameworkType.Vue:
                    sb.AppendLine("import { useQuery, useMutation } from '@tanstack/vue-query';");
                    break;
                case FrameworkType.Svelte:
                    sb.AppendLine("import { createQuery, createMutation } from '@tanstack/svelte-query';");
                    break;
                default:
                    sb.AppendLine("import { useQuery, useMutation } from '@tanstack/react-query';");
                    break;
            }

            bool needsFormData = controllerType.GetMethods()
                .Any(m => m.GetParameters()
                    .Any(p => p.GetCustomAttributes(true)
                        .Any(a => a.GetType().Name == "FromFormAttribute")));

            if (needsFormData)
            {
                sb.AppendLine("import { apiRequest, serializeToFormData } from '../apiClient';");
            }
            else
            {
                sb.AppendLine("import { apiRequest } from '../apiClient';");
            }

            var deps = resolver.GetControllerDependencies(controllerType);
            foreach (var dep in deps.OrderBy(d => d.Name))
            {
                var name = dep.IsGenericTypeDefinition ? dep.Name.Split('`')[0] : dep.Name;
                var zodImport = _zodEnabledTypes.Contains(dep) ? $", {name}Schema" : "";
                sb.AppendLine($"import {{ {name}{zodImport} }} from '../models/{name}';");
            }
            sb.AppendLine();

            GenerateControllerHooks(sb, controllerType, resolver, framework);
            return sb.ToString();
        }

        private void GenerateControllerHooks(StringBuilder sb, Type controllerType, DependencyResolver resolver, FrameworkType framework)
        {
            var methods = controllerType.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            string controllerName = controllerType.Name.Replace("Controller", "");
            
            var routeAttr = controllerType.GetCustomAttributes(true)
                .FirstOrDefault(a => a.GetType().Name == "RouteAttribute");
                
            string baseRoute = "api/" + controllerName.ToLower();
            if (routeAttr != null)
            {
                var templateProp = routeAttr.GetType().GetProperty("Template");
                var tmpl = templateProp?.GetValue(routeAttr)?.ToString();
                if (!string.IsNullOrEmpty(tmpl))
                {
                    baseRoute = tmpl.Replace("[controller]", controllerName.ToLower());
                }
            }

            foreach (var method in methods)
            {
                GenerateMethodHooks(sb, method, controllerType, baseRoute, resolver, framework);
            }
        }

        private void GenerateMethodHooks(StringBuilder sb, MethodInfo method, Type controllerType, string baseRoute, DependencyResolver resolver, FrameworkType framework)
        {
            var httpAttr = method.GetCustomAttributes(true)
                .FirstOrDefault(a => a.GetType().Name.StartsWith("Http") && a.GetType().Name.EndsWith("Attribute"));
            
            var methodRouteAttr = method.GetCustomAttributes(true)
                .FirstOrDefault(a => a.GetType().Name == "RouteAttribute");
                
            if (httpAttr == null && methodRouteAttr == null) return;

            string httpMethod = httpAttr?.GetType().Name.Replace("Http", "").Replace("Attribute", "").ToUpper() ?? "GET";
            var templateProp = (httpAttr ?? methodRouteAttr).GetType().GetProperty("Template");
            string methodRoute = templateProp?.GetValue(httpAttr ?? methodRouteAttr)?.ToString() ?? "";

            string finalUrl = baseRoute;
            if (!string.IsNullOrEmpty(methodRoute))
            {
                finalUrl = methodRoute.StartsWith("/") ? methodRoute.Substring(1) : $"{baseRoute}/{methodRoute}";
            }

            var parameters = method.GetParameters();
            var queryParams = new List<string>();
            var routeParams = new List<string>();
            string? bodyParamName = null;
            string? formParamName = null;
            var tsFuncParams = new List<string>();
            var callArgs = new List<string>();

            foreach (var p in parameters)
            {
                bool isFromBody = p.GetCustomAttributes(true).Any(a => a.GetType().Name == "FromBodyAttribute");
                bool isFromForm = p.GetCustomAttributes(true).Any(a => a.GetType().Name == "FromFormAttribute");
                // bool isFromQuery = p.GetCustomAttributes(true).Any(a => a.GetType().Name == "FromQueryAttribute");
                bool isFromRoute = p.GetCustomAttributes(true).Any(a => a.GetType().Name == "FromRouteAttribute");

                string tsName = TypeMapper.CamelCase(p.Name);
                string tsType = TypeMapper.MapCSharpToTypeScript(p.ParameterType);

                if (isFromBody) bodyParamName = tsName;
                else if (isFromForm) formParamName = tsName;
                else if (isFromRoute || finalUrl.Contains($"{{{p.Name}}}")) routeParams.Add(p.Name);
                else queryParams.Add(p.Name);

                tsFuncParams.Add($"{tsName}: {tsType}");
                callArgs.Add(tsName);
            }

            foreach (var rp in routeParams)
            {
                finalUrl = finalUrl.Replace($"{{{rp}}}", $"${{{TypeMapper.CamelCase(rp)}}}");
            }

            string funcName = TypeMapper.CamelCase(method.Name);
            string funcArgs = string.Join(", ", tsFuncParams);
            var returnType = TypeMapper.MapCSharpToTypeScript(resolver.GetUnwrappedReturnType(method.ReturnType));

            sb.AppendLine($"export const {funcName}Request = async ({funcArgs}) => {{");
            
            string bodyArgument = formParamName != null ? "serializeToFormData(" + formParamName + ")" : (bodyParamName ?? "null");
            string tsParamsObject = queryParams.Any() ? "{ " + string.Join(", ", queryParams.Select(TypeMapper.CamelCase)) + " }" : "null";
            string urlQuote = finalUrl.Contains("${") ? "`" : "'";

            sb.AppendLine($"    return await apiRequest<{returnType}>({urlQuote}{finalUrl}{urlQuote}, '{httpMethod}', {bodyArgument}, {tsParamsObject});");
            sb.AppendLine("};");
            sb.AppendLine();

            if (httpMethod == "GET")
            {
                GenerateQueryHook(sb, funcName, method.Name, controllerType.Name, tsFuncParams, callArgs, framework);
            }
            else
            {
                GenerateMutationHook(sb, funcName, method.Name, tsFuncParams, callArgs, framework);
            }
        }

        private void GenerateQueryHook(StringBuilder sb, string funcName, string methodName, string controllerName, List<string> tsFuncParams, List<string> callArgs, FrameworkType framework)
        {
            string funcArgs = string.Join(", ", tsFuncParams);
            string callArgsStr = string.Join(", ", callArgs);
            var queryKeyParams = callArgs.Any() ? ", " + string.Join(", ", callArgs) : "";
            
            string hookName = framework == FrameworkType.Svelte ? "createQuery" : "useQuery";
            string funcPrefix = framework == FrameworkType.Svelte ? "create" : "use";

            sb.AppendLine($"export const {funcPrefix}{methodName}Query = ({funcArgs}) => {{");
            sb.AppendLine($"    return {hookName}({{");
            sb.AppendLine($"        queryKey: ['{controllerName}', '{methodName}'{queryKeyParams}],");
            sb.AppendLine($"        queryFn: () => {funcName}Request({callArgsStr}),");
            sb.AppendLine($"    }});");
            sb.AppendLine("};");
            sb.AppendLine();
        }

        private void GenerateMutationHook(StringBuilder sb, string funcName, string methodName, List<string> tsFuncParams, List<string> callArgs, FrameworkType framework)
        {
            string mutationSignature;
            string requestArgs;

            if (callArgs.Count == 0)
            {
                mutationSignature = "()";
                requestArgs = "";
            }
            else if (callArgs.Count == 1)
            {
                mutationSignature = $"({callArgs[0]}: {tsFuncParams[0].Split(':')[1].Trim()})";
                requestArgs = callArgs[0];
            }
            else
            {
                mutationSignature = "({ " + string.Join(", ", callArgs) + " }: { " + string.Join("; ", tsFuncParams) + " })";
                requestArgs = string.Join(", ", callArgs);
            }

            string hookName = framework == FrameworkType.Svelte ? "createMutation" : "useMutation";
            string funcPrefix = framework == FrameworkType.Svelte ? "create" : "use";

            sb.AppendLine($"export const {funcPrefix}{methodName}Mutation = () => {{");
            sb.AppendLine($"    return {hookName}({{");
            sb.AppendLine($"        mutationFn: {mutationSignature} => {funcName}Request({requestArgs}),");
            sb.AppendLine($"    }});");
            sb.AppendLine("};");
            sb.AppendLine();
        }
    }
}
