using System;
using System.Reflection;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace SharpSync.Core.Generators
{
    public class HubGenerator
    {
        private readonly HashSet<Type> _zodEnabledTypes;

        public HubGenerator(HashSet<Type> zodEnabledTypes)
        {
            _zodEnabledTypes = zodEnabledTypes;
        }

        public string GenerateHubFile(Type hubType, DependencyResolver resolver, FrameworkType framework)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SharpSync");
            
            // Note: Users will need to install @microsoft/signalr
            sb.AppendLine("import { HubConnection, HubConnectionBuilder } from '@microsoft/signalr';");

            var deps = resolver.GetHubDependencies(hubType);
            foreach (var dep in deps.OrderBy(d => d.Name))
            {
                var name = dep.IsGenericTypeDefinition ? dep.Name.Split('`')[0] : dep.Name;
                var zodImport = _zodEnabledTypes.Contains(dep) ? $", {name}Schema" : "";
                sb.AppendLine($"import {{ {name}{zodImport} }} from '../models/{name}';");
            }
            sb.AppendLine();

            string hubName = hubType.Name.Replace("Hub", "");
            string className = $"{hubName}HubClient";

            GenerateHubClientClass(sb, className, hubType, resolver);
            
            if (framework == FrameworkType.React)
            {
                GenerateReactHook(sb, hubName, className);
            }
            // We can add Vue/Svelte specific helpers if needed, but a class is a good start.

            return sb.ToString();
        }

        private void GenerateHubClientClass(StringBuilder sb, string className, Type hubType, DependencyResolver resolver)
        {
            sb.AppendLine($"export class {className} {{");
            sb.AppendLine("    constructor(public connection: HubConnection) {}");
            sb.AppendLine();

            // 1. Server Methods (Client -> Server)
            sb.AppendLine("    // Server Methods (Client -> Server)");
            var serverMethods = hubType.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            foreach (var method in serverMethods)
            {
                var parameters = method.GetParameters();
                var tsParams = string.Join(", ", parameters.Select(p => $"{TypeMapper.CamelCase(p.Name)}: {TypeMapper.MapCSharpToTypeScript(p.ParameterType)}"));
                var callParams = string.Join(", ", parameters.Select(p => TypeMapper.CamelCase(p.Name)));
                var returnType = TypeMapper.MapCSharpToTypeScript(resolver.GetUnwrappedReturnType(method.ReturnType));

                sb.AppendLine($"    async {TypeMapper.CamelCase(method.Name)}({tsParams}): Promise<{returnType}> {{");
                sb.AppendLine($"        return await this.connection.invoke('{method.Name}'{(string.IsNullOrEmpty(callParams) ? "" : ", " + callParams)});");
                sb.AppendLine("    }");
            }
            sb.AppendLine();

            // 2. Client Methods (Server -> Client)
            sb.AppendLine("    // Client Methods (Server -> Client)");
            var clientType = resolver.GetHubClientType(hubType);
            if (clientType != null)
            {
                var clientMethods = clientType.GetMethods();
                foreach (var method in clientMethods)
                {
                    var parameters = method.GetParameters();
                    var tsParams = string.Join(", ", parameters.Select(p => $"{TypeMapper.CamelCase(p.Name)}: {TypeMapper.MapCSharpToTypeScript(p.ParameterType)}"));
                    var paramNames = string.Join(", ", parameters.Select(p => TypeMapper.CamelCase(p.Name)));

                    sb.AppendLine($"    on{method.Name}(callback: ({tsParams}) => void) {{");
                    sb.AppendLine($"        this.connection.on('{method.Name}', ({paramNames}) => {{");
                    sb.AppendLine($"            callback({paramNames});");
                    sb.AppendLine("        });");
                    sb.AppendLine("        return () => this.connection.off('{method.Name}', callback);");
                    sb.AppendLine("    }");
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        private void GenerateReactHook(StringBuilder sb, string hubName, string className)
        {
            sb.AppendLine("import { useEffect, useState } from 'react';");
            sb.AppendLine();
            sb.AppendLine($"export const use{hubName}Hub = (url: string) => {{");
            sb.AppendLine($"    const [client, setClient] = useState<{className} | null>(null);");
            sb.AppendLine();
            sb.AppendLine("    useEffect(() => {");
            sb.AppendLine("        const connection = new HubConnectionBuilder()");
            sb.AppendLine("            .withUrl(url)");
            sb.AppendLine("            .withAutomaticReconnect()");
            sb.AppendLine("            .build();");
            sb.AppendLine();
            sb.AppendLine($"        const hubClient = new {className}(connection);");
            sb.AppendLine("        ");
            sb.AppendLine("        connection.start()");
            sb.AppendLine("            .then(() => setClient(hubClient))");
            sb.AppendLine("            .catch(err => console.error('SignalR Connection Error: ', err));");
            sb.AppendLine();
            sb.AppendLine("        return () => {");
            sb.AppendLine("            connection.stop();");
            sb.AppendLine("        };");
            sb.AppendLine("    }, [url]);");
            sb.AppendLine();
            sb.AppendLine("    return client;");
            sb.AppendLine("};");
        }
    }
}
