using System;
using System.Reflection;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace SharpSync.Core.Generators
{
    public class ModelGenerator
    {
        private readonly HashSet<Type> _zodEnabledTypes;

        public ModelGenerator(HashSet<Type> zodEnabledTypes)
        {
            _zodEnabledTypes = zodEnabledTypes;
        }

        public string GenerateModelFile(Type type, DependencyResolver resolver)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SharpSync");

            var deps = resolver.GetTypeDependencies(type);
            foreach (var dep in deps.OrderBy(d => d.Name))
            {
                var zodImport = _zodEnabledTypes.Contains(dep) ? $", {dep.Name}Schema" : "";
                sb.AppendLine($"import {{ {dep.Name}{zodImport} }} from './{dep.Name}';");
            }

            if (_zodEnabledTypes.Contains(type))
            {
                sb.AppendLine("import { z } from 'zod';");
            }
            sb.AppendLine();

            GenerateModelContent(sb, type);
            return sb.ToString();
        }

        private void GenerateModelContent(StringBuilder sb, Type type)
        {
            if (type.IsEnum)
            {
                sb.AppendLine($"export enum {type.Name} {{");
                foreach (var name in Enum.GetNames(type))
                {
                    sb.AppendLine($"    {name} = '{name}',");
                }
                sb.AppendLine("}");
            }
            else
            {
                var metadata = new List<string>();
                sb.AppendLine($"export interface {type.Name} {{");
                foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                {
                    var tsType = TypeMapper.MapCSharpToTypeScript(prop.PropertyType);
                    sb.AppendLine($"    {TypeMapper.CamelCase(prop.Name)}: {tsType};");

                    var rules = ExtractMetadataRules(prop);
                    if (rules.Any())
                    {
                        metadata.Add($"    {TypeMapper.CamelCase(prop.Name)}: {{ {string.Join(", ", rules)} }}");
                    }
                }
                sb.AppendLine("}");

                if (_zodEnabledTypes.Contains(type))
                {
                    GenerateZodSchema(sb, type);
                }

                if (metadata.Any())
                {
                    sb.AppendLine();
                    sb.AppendLine($"export const {type.Name}Metadata = {{");
                    sb.AppendLine(string.Join(",\n", metadata));
                    sb.AppendLine("};");
                }
            }
        }

        private void GenerateZodSchema(StringBuilder sb, Type type)
        {
            sb.AppendLine();
            sb.AppendLine($"export const {type.Name}Schema = z.object({{");
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var zodBase = TypeMapper.MapCSharpToZod(prop.PropertyType, _zodEnabledTypes);
                var rules = TypeMapper.GetZodRules(prop);
                var zodSchema = zodBase + string.Join("", rules);
                sb.AppendLine($"    {TypeMapper.CamelCase(prop.Name)}: {zodSchema},");
            }
            sb.AppendLine("});");
        }

        private List<string> ExtractMetadataRules(PropertyInfo prop)
        {
            var rules = new List<string>();
            foreach (var attr in prop.GetCustomAttributes(true))
            {
                var attrType = attr.GetType();
                if (attrType.Name == "RequiredAttribute") rules.Add("required: true");
                else if (attrType.Name == "StringLengthAttribute")
                {
                    var max = attrType.GetProperty("MaximumLength")?.GetValue(attr);
                    var min = attrType.GetProperty("MinimumLength")?.GetValue(attr);
                    if (max != null) rules.Add($"maxLength: {max}");
                    if (min != null && (int)min > 0) rules.Add($"minLength: {min}");
                }
                else if (attrType.Name == "MaxLengthAttribute")
                {
                    var max = attrType.GetProperty("Length")?.GetValue(attr);
                    if (max != null) rules.Add($"maxLength: {max}");
                }
                else if (attrType.Name == "MinLengthAttribute")
                {
                    var min = attrType.GetProperty("Length")?.GetValue(attr);
                    if (min != null) rules.Add($"minLength: {min}");
                }
                else if (attrType.Name == "RangeAttribute")
                {
                    var min = attrType.GetProperty("Minimum")?.GetValue(attr);
                    var max = attrType.GetProperty("Maximum")?.GetValue(attr);
                    if (min != null || max != null)
                    {
                        var rangeParts = new List<string>();
                        if (min != null) rangeParts.Add($"min: {min}");
                        if (max != null) rangeParts.Add($"max: {max}");
                        rules.Add($"range: {{ {string.Join(", ", rangeParts)} }}");
                    }
                }
            }
            return rules;
        }
    }
}
