using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using SharpSync.Core.Plugins;

namespace SharpSync.Core.Generators
{
    public class TypeScriptCodeGenerator : ICodeGenerator
    {
        public string Generate(IEnumerable<Type> types)
        {
            var discoveredTypes = CollectTypesRecursive(types);
            
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SharpSync");
            sb.AppendLine("import { useQuery, useMutation } from '@tanstack/react-query';");
            sb.AppendLine("import { apiRequest } from './apiClient'; // Ensure you have an apiClient.ts exporting an apiRequest function.");
            sb.AppendLine();

            // Separate controllers from models
            var controllers = discoveredTypes.Where(t => t.Name.EndsWith("Controller")).ToList();
            var models = discoveredTypes.Where(t => !t.Name.EndsWith("Controller")).ToList();

            foreach (var model in models)
            {
                GenerateTypeInterface(sb, model);
            }

            foreach (var controller in controllers)
            {
                GenerateControllerHooks(sb, controller);
            }

            return sb.ToString();
        }

        private HashSet<Type> CollectTypesRecursive(IEnumerable<Type> initialTypes)
        {
            var discovered = new HashSet<Type>();
            var queue = new Queue<Type>(initialTypes);

            while (queue.Count > 0)
            {
                var type = queue.Dequeue();
                if (type == null || discovered.Contains(type) || IsSystemType(type)) continue;

                discovered.Add(type);

                if (type.Name.EndsWith("Controller"))
                {
                    var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
                    foreach (var m in methods)
                    {
                        // Return type
                        var retType = GetUnwrappedReturnType(m.ReturnType);
                        EnqueueType(queue, retType, discovered);

                        // Parameters
                        foreach (var p in m.GetParameters())
                        {
                            EnqueueType(queue, p.ParameterType, discovered);
                        }
                    }
                }
                else
                {
                    // For DTOs, explore properties
                    foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                    {
                        EnqueueType(queue, prop.PropertyType, discovered);
                    }
                }
            }

            return discovered;
        }

        private void EnqueueType(Queue<Type> queue, Type type, HashSet<Type> discovered)
        {
            if (type.IsGenericType)
            {
                foreach (var arg in type.GetGenericArguments())
                    EnqueueType(queue, arg, discovered);
                return;
            }

            if (type.IsArray)
            {
                EnqueueType(queue, type.GetElementType()!, discovered);
                return;
            }

            if (!IsSystemType(type) && !discovered.Contains(type))
            {
                queue.Enqueue(type);
            }
        }

        private bool IsSystemType(Type type)
        {
            return type.Namespace != null && (type.Namespace.StartsWith("System") || type.Namespace.StartsWith("Microsoft"));
        }

        private void GenerateTypeInterface(StringBuilder sb, Type type)
        {
            if (type.IsEnum)
            {
                sb.AppendLine($"export enum {type.Name} {{");
                foreach (var name in Enum.GetNames(type))
                {
                    sb.AppendLine($"    {name} = '{name}',");
                }
                sb.AppendLine("}");
            }
            else
            {
                sb.AppendLine($"export interface {type.Name} {{");
                foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                {
                    var tsType = MapCSharpToTypeScript(prop.PropertyType);
                    sb.AppendLine($"    {CamelCase(prop.Name)}: {tsType};");
                }
                sb.AppendLine("}");
            }
            sb.AppendLine();
        }

        private void GenerateControllerHooks(StringBuilder sb, Type controllerType)
        {
            var methods = controllerType.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            
            string controllerName = controllerType.Name.Replace("Controller", "");
            var routeAttr = controllerType.GetCustomAttributes(true)
                .FirstOrDefault(a => a.GetType().Name == "RouteAttribute");
                
            string baseRoute = "api/" + controllerName.ToLower();
            if (routeAttr != null)
            {
                var templateProp = routeAttr.GetType().GetProperty("Template");
                var tmpl = templateProp?.GetValue(routeAttr)?.ToString();
                if (!string.IsNullOrEmpty(tmpl))
                {
                    baseRoute = tmpl.Replace("[controller]", controllerName.ToLower());
                }
            }

            foreach (var method in methods)
            {
                var httpAttr = method.GetCustomAttributes(true)
                    .FirstOrDefault(a => a.GetType().Name.StartsWith("Http") && a.GetType().Name.EndsWith("Attribute"));
                
                var methodRouteAttr = method.GetCustomAttributes(true)
                    .FirstOrDefault(a => a.GetType().Name == "RouteAttribute");
                    
                if (httpAttr == null && methodRouteAttr == null) continue;

                string httpMethod = "GET"; 
                if (httpAttr != null)
                {
                    string attrName = httpAttr.GetType().Name;
                    httpMethod = attrName.Replace("Http", "").Replace("Attribute", "").ToUpper();
                }

                string actionRoute = "";
                if (httpAttr != null)
                {
                    var templateProp = httpAttr.GetType().GetProperty("Template");
                    actionRoute = templateProp?.GetValue(httpAttr)?.ToString() ?? "";
                }
                
                if (string.IsNullOrEmpty(actionRoute) && methodRouteAttr != null)
                {
                    var templateProp = methodRouteAttr.GetType().GetProperty("Template");
                    actionRoute = templateProp?.GetValue(methodRouteAttr)?.ToString() ?? "";
                }

                string fullRoute;
                if (actionRoute.StartsWith("/") || actionRoute.StartsWith("~/"))
                {
                    fullRoute = actionRoute.TrimStart('~').TrimStart('/');
                }
                else
                {
                    string sanitizedBase = baseRoute.TrimEnd('/');
                    string sanitizedAction = actionRoute.TrimStart('/');
                    fullRoute = string.IsNullOrEmpty(sanitizedAction) ? sanitizedBase : $"{sanitizedBase}/{sanitizedAction}";
                }

                // --- Robust Parameter Mapping ---
                var routeParams = System.Text.RegularExpressions.Regex.Matches(fullRoute, @"\{(?<param>.*?)\}")
                    .Cast<System.Text.RegularExpressions.Match>()
                    .Select(m => m.Groups["param"].Value)
                    .ToList();

                var methodParameters = method.GetParameters();
                var tsFuncParams = new List<string>();
                var tsQueryParams = new List<string>();
                var tsQuerySpreads = new List<string>();
                
                var finalUrl = fullRoute;

                // 1. Identify Path Parameters
                foreach (var paramName in routeParams)
                {
                    var csharpParam = methodParameters.FirstOrDefault(p => string.Equals(p.Name, paramName, StringComparison.OrdinalIgnoreCase));
                    string tsType = csharpParam != null ? MapCSharpToTypeScript(csharpParam.ParameterType) : "any";
                    
                    tsFuncParams.Add($"{CamelCase(paramName)}: {tsType}");
                    finalUrl = finalUrl.Replace("{" + paramName + "}", "${" + CamelCase(paramName) + "}");
                }

                // 2. Identify Query and Body Parameters
                string? bodyParamName = null;
                foreach (var param in methodParameters)
                {
                    if (routeParams.Any(rp => string.Equals(rp, param.Name, StringComparison.OrdinalIgnoreCase)))
                        continue;

                    bool isFromQuery = param.GetCustomAttributes(true).Any(a => a.GetType().Name == "FromQueryAttribute");
                    bool isFromBody = param.GetCustomAttributes(true).Any(a => a.GetType().Name == "FromBodyAttribute");
                    bool isSimple = IsSimpleType(param.ParameterType);

                    if (isFromQuery || (httpMethod == "GET" && isSimple))
                    {
                        string tsType = MapCSharpToTypeScript(param.ParameterType);
                        tsFuncParams.Add($"{CamelCase(param.Name)}: {tsType}");
                        
                        if (isSimple)
                            tsQueryParams.Add(CamelCase(param.Name));
                        else
                            tsQuerySpreads.Add(CamelCase(param.Name));
                    }
                    else if (isFromBody || (!isSimple && httpMethod != "GET"))
                    {
                        bodyParamName = CamelCase(param.Name);
                        string tsType = MapCSharpToTypeScript(param.ParameterType);
                        tsFuncParams.Add($"{bodyParamName}: {tsType}");
                    }
                }

                string returnType = MapCSharpToTypeScript(GetUnwrappedReturnType(method.ReturnType));
                string funcName = CamelCase(method.Name);
                
                string funcArgs = string.Join(", ", tsFuncParams);
                string callArgs = string.Join(", ", tsFuncParams.Select(p => p.Split(':')[0].Trim()));
                
                // Construct the params object for the TS call
                string tsParamsObject;
                if (tsQueryParams.Count == 0 && tsQuerySpreads.Count == 1)
                {
                    tsParamsObject = tsQuerySpreads[0]; // Direct DTO pass
                }
                else if (tsQueryParams.Count > 0 || tsQuerySpreads.Count > 0)
                {
                    var parts = tsQueryParams.Select(q => q).Concat(tsQuerySpreads.Select(s => $"...{s}"));
                    tsParamsObject = "{ " + string.Join(", ", parts) + " }";
                }
                else
                {
                    tsParamsObject = "null";
                }

                string bodyArgument = bodyParamName ?? "null";
                string urlQuote = routeParams.Any() ? "`" : "'";

                var allKeyParams = tsFuncParams.Select(p => p.Split(':')[0].Trim()).ToList();
                string queryKeyParams = allKeyParams.Any() ? ", " + string.Join(", ", allKeyParams) : "";

                sb.AppendLine($"export const {funcName}Request = async ({funcArgs}) => {{");
                sb.AppendLine($"    return await apiRequest<{returnType}>({urlQuote}{finalUrl}{urlQuote}, '{httpMethod}', {bodyArgument}, {tsParamsObject});");
                sb.AppendLine($"}};");
                sb.AppendLine();

                if (httpMethod == "GET")
                {
                    sb.AppendLine($"export const use{method.Name}Query = ({funcArgs}) => {{");
                    sb.AppendLine($"    return useQuery({{");
                    sb.AppendLine($"        queryKey: ['{controllerType.Name}', '{method.Name}'{queryKeyParams}],");
                    sb.AppendLine($"        queryFn: () => {funcName}Request({callArgs}),");
                    sb.AppendLine($"    }});");
                    sb.AppendLine($"}};");
                }
                else
                {
                    // For mutations, if multiple arguments exist, wrap them in an object for useMutation
                    var allArgs = tsFuncParams.Select(p => p.Split(':')[0].Trim()).ToList();
                    string mutationSignature;
                    string requestArgs;

                    if (allArgs.Count == 0)
                    {
                        mutationSignature = "()";
                        requestArgs = "";
                    }
                    else if (allArgs.Count == 1)
                    {
                        var arg = allArgs[0];
                        var type = tsFuncParams[0].Split(':')[1].Trim();
                        mutationSignature = $"({arg}: {type})";
                        requestArgs = arg;
                    }
                    else
                    {
                        // Multiple arguments: wrap in object
                        mutationSignature = "({ " + string.Join(", ", allArgs) + " }: { " + string.Join("; ", tsFuncParams) + " })";
                        requestArgs = string.Join(", ", allArgs);
                    }

                    sb.AppendLine($"export const use{method.Name}Mutation = () => {{");
                    sb.AppendLine($"    return useMutation({{");
                    sb.AppendLine($"        mutationFn: {mutationSignature} => {funcName}Request({requestArgs}),");
                    sb.AppendLine($"    }});");
                    sb.AppendLine($"}};");
                }
                sb.AppendLine();
            }
        }

        private bool IsSimpleType(Type type)
        {
            Type? underlying = Nullable.GetUnderlyingType(type);
            if (underlying != null) type = underlying;

            return type.IsPrimitive || 
                   type == typeof(string) || 
                   type == typeof(decimal) || 
                   type == typeof(DateTime) || 
                   type == typeof(DateTimeOffset) || 
                   type == typeof(DateOnly) || 
                   type == typeof(TimeOnly) || 
                   type == typeof(Guid) ||
                   type.IsEnum;
        }

        private Type GetUnwrappedReturnType(Type returnType)
        {
            if (returnType.IsGenericType && (returnType.Name.StartsWith("Task") || returnType.Name.StartsWith("ValueTask")))
            {
                return returnType.GetGenericArguments().FirstOrDefault() ?? typeof(void);
            }
            if (returnType.IsGenericType && returnType.Name.StartsWith("ActionResult"))
            {
                return returnType.GetGenericArguments().FirstOrDefault() ?? typeof(void);
            }
            return returnType;
        }

        private string MapCSharpToTypeScript(Type type)
        {
            if (Nullable.GetUnderlyingType(type) != null)
                type = Nullable.GetUnderlyingType(type)!;

            if (type == typeof(int) || type == typeof(double) || type == typeof(float) || type == typeof(decimal) || type == typeof(long))
                return "number";
            if (type == typeof(string) || type == typeof(Guid) || type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(DateOnly) || type == typeof(TimeOnly))
                return "string";
            if (type == typeof(bool))
                return "boolean";
            if (type.IsArray)
                return MapCSharpToTypeScript(type.GetElementType()!) + "[]";
            
            if (type.IsGenericType)
            {
                var genDef = type.GetGenericTypeDefinition();
                if (genDef == typeof(IEnumerable<>) || genDef == typeof(List<>) || genDef == typeof(IList<>) || genDef == typeof(ICollection<>))
                {
                    var elType = type.GetGenericArguments().First();
                    return MapCSharpToTypeScript(elType) + "[]";
                }
            }
            
            if (type == typeof(void)) return "void";

            return type.Name; // Represents a custom DTO class/interface
        }

        private string CamelCase(string str)
        {
            if (string.IsNullOrEmpty(str)) return str;
            return char.ToLowerInvariant(str[0]) + str.Substring(1);
        }
    }
}
