using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using SharpSync.Core.Plugins;

namespace SharpSync.Core.Generators
{
    public class TypeScriptCodeGenerator : ICodeGenerator
    {
        public string Generate(IEnumerable<Type> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SharpSync");
            sb.AppendLine("import { useQuery, useMutation } from '@tanstack/react-query';");
            sb.AppendLine("import { apiRequest } from './apiClient'; // Ensure you have an apiClient.ts exporting an apiRequest function.");
            sb.AppendLine();

            foreach (var type in types)
            {
                if (type.Name.EndsWith("Controller"))
                {
                    GenerateControllerHooks(sb, type);
                }
                else
                {
                    GenerateTypeInterface(sb, type);
                }
            }

            return sb.ToString();
        }

        private void GenerateTypeInterface(StringBuilder sb, Type type)
        {
            sb.AppendLine($"export interface {type.Name} {{");
            foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var tsType = MapCSharpToTypeScript(prop.PropertyType);
                sb.AppendLine($"    {CamelCase(prop.Name)}: {tsType};");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private void GenerateControllerHooks(StringBuilder sb, Type controllerType)
        {
            var methods = controllerType.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            
            string controllerName = controllerType.Name.Replace("Controller", "");
            var routeAttr = controllerType.GetCustomAttributes(true)
                .FirstOrDefault(a => a.GetType().Name == "RouteAttribute");
                
            string baseRoute = "api/" + controllerName.ToLower();
            if (routeAttr != null)
            {
                var templateProp = routeAttr.GetType().GetProperty("Template");
                var tmpl = templateProp?.GetValue(routeAttr)?.ToString();
                if (!string.IsNullOrEmpty(tmpl))
                {
                    baseRoute = tmpl.Replace("[controller]", controllerName.ToLower());
                }
            }

            foreach (var method in methods)
            {
                // Find HttpVerb attribute (HttpGet, HttpPost, etc.)
                var httpAttr = method.GetCustomAttributes(true)
                    .FirstOrDefault(a => a.GetType().Name.StartsWith("Http") && a.GetType().Name.EndsWith("Attribute"));
                
                // Find [Route] attribute on method
                var methodRouteAttr = method.GetCustomAttributes(true)
                    .FirstOrDefault(a => a.GetType().Name == "RouteAttribute");
                    
                if (httpAttr == null && methodRouteAttr == null) continue;

                string httpMethod = "GET"; 
                if (httpAttr != null)
                {
                    string attrName = httpAttr.GetType().Name;
                    httpMethod = attrName.Replace("Http", "").Replace("Attribute", "").ToUpper();
                }

                // Resolve the action route template
                string actionRoute = "";
                if (httpAttr != null)
                {
                    var templateProp = httpAttr.GetType().GetProperty("Template");
                    actionRoute = templateProp?.GetValue(httpAttr)?.ToString() ?? "";
                }
                
                if (string.IsNullOrEmpty(actionRoute) && methodRouteAttr != null)
                {
                    var templateProp = methodRouteAttr.GetType().GetProperty("Template");
                    actionRoute = templateProp?.GetValue(methodRouteAttr)?.ToString() ?? "";
                }

                // Handle absolute vs relative routes
                string fullRoute;
                if (actionRoute.StartsWith("/") || actionRoute.StartsWith("~/"))
                {
                    // Absolute route (overrides controller route)
                    fullRoute = actionRoute.TrimStart('~').TrimStart('/');
                }
                else
                {
                    // Relative route (appends to controller base)
                    string sanitizedBase = baseRoute.TrimEnd('/');
                    string sanitizedAction = actionRoute.TrimStart('/');
                    fullRoute = string.IsNullOrEmpty(sanitizedAction) ? sanitizedBase : $"{sanitizedBase}/{sanitizedAction}";
                }

                string returnType = MapCSharpToTypeScript(GetUnwrappedReturnType(method.ReturnType));
                string funcName = CamelCase(method.Name);
                
                sb.AppendLine($"export const {funcName}Request = async () => {{");
                sb.AppendLine($"    return await apiRequest<{returnType}>('{fullRoute}', '{httpMethod}');");
                sb.AppendLine($"}};");
                sb.AppendLine();

                if (httpMethod == "GET")
                {
                    sb.AppendLine($"export const use{method.Name}Query = () => {{");
                    sb.AppendLine($"    return useQuery({{");
                    sb.AppendLine($"        queryKey: ['{controllerType.Name}', '{method.Name}'],");
                    sb.AppendLine($"        queryFn: () => {funcName}Request(),");
                    sb.AppendLine($"    }});");
                    sb.AppendLine($"}};");
                }
                else
                {
                    sb.AppendLine($"export const use{method.Name}Mutation = () => {{");
                    sb.AppendLine($"    return useMutation({{");
                    sb.AppendLine($"        mutationFn: () => {funcName}Request(),");
                    sb.AppendLine($"    }});");
                    sb.AppendLine($"}};");
                }
                sb.AppendLine();
            }
        }

        private Type GetUnwrappedReturnType(Type returnType)
        {
            if (returnType.IsGenericType && returnType.GetGenericTypeDefinition().Name.StartsWith("Task"))
            {
                return returnType.GetGenericArguments().FirstOrDefault() ?? typeof(void);
            }
            if (returnType.IsGenericType && returnType.GetGenericTypeDefinition().Name.StartsWith("ActionResult"))
            {
                return returnType.GetGenericArguments().FirstOrDefault() ?? typeof(void);
            }
            return returnType;
        }

        private string MapCSharpToTypeScript(Type type)
        {
            // Nullable mapping
            if (Nullable.GetUnderlyingType(type) != null)
                type = Nullable.GetUnderlyingType(type)!;

            if (type == typeof(int) || type == typeof(double) || type == typeof(float) || type == typeof(decimal))
                return "number";
            if (type == typeof(string) || type == typeof(Guid))
                return "string";
            if (type == typeof(bool))
                return "boolean";
            if (type == typeof(DateTime) || type == typeof(DateTimeOffset) || type == typeof(DateOnly) || type == typeof(TimeOnly))
                return "string";
            if (type.IsArray)
                return MapCSharpToTypeScript(type.GetElementType()!) + "[]";
            
            if (type.IsGenericType)
            {
                var genDef = type.GetGenericTypeDefinition();
                if (genDef == typeof(IEnumerable<>) || genDef == typeof(List<>) || genDef == typeof(IList<>) || genDef == typeof(ICollection<>))
                {
                    var elType = type.GetGenericArguments().First();
                    return MapCSharpToTypeScript(elType) + "[]";
                }
            }
            
            if (type == typeof(void)) return "void";

            return type.Name; // Represents a custom DTO class/interface
        }

        private string CamelCase(string str)
        {
            if (string.IsNullOrEmpty(str)) return str;
            return char.ToLowerInvariant(str[0]) + str.Substring(1);
        }
    }
}
