// Auto-generated by SharpSync
import { useQuery, useMutation } from '@tanstack/react-query';
import { apiRequest, serializeToFormData } from '../apiClient';
import { CreateForecastDto, CreateForecastDtoSchema } from '../models/CreateForecastDto';
import { DemoForecast, DemoForecastSchema } from '../models/DemoForecast';
import { SearchFilter } from '../models/SearchFilter';
import { UploadReportDto } from '../models/UploadReportDto';

export const getRequest = async () => {
    return await apiRequest<DemoForecast[]>('api/v1/demoforecast/all', 'GET', null, null);
};

export const useGetQuery = () => {
    return useQuery({
        queryKey: ['DemoForecastController', 'Get'],
        queryFn: () => getRequest(),
    });
};

export const getByIdRequest = async (id: number) => {
    return await apiRequest<DemoForecast>(`api/v1/demoforecast/${id}`, 'GET', null, null);
};

export const useGetByIdQuery = (id: number) => {
    return useQuery({
        queryKey: ['DemoForecastController', 'GetById', id],
        queryFn: () => getByIdRequest(id),
    });
};

export const getStatsRequest = async () => {
    return await apiRequest<string>('global-stats', 'GET', null, null);
};

export const useGetStatsQuery = () => {
    return useQuery({
        queryKey: ['DemoForecastController', 'GetStats'],
        queryFn: () => getStatsRequest(),
    });
};

export const searchRequest = async (q: string, minTemp: number | null) => {
    return await apiRequest<DemoForecast[]>('api/v1/demoforecast/search', 'GET', null, { q, minTemp });
};

export const useSearchQuery = (q: string, minTemp: number | null) => {
    return useQuery({
        queryKey: ['DemoForecastController', 'Search', q, minTemp],
        queryFn: () => searchRequest(q, minTemp),
    });
};

export const advancedSearchRequest = async (filter: SearchFilter, page: number) => {
    return await apiRequest<DemoForecast[]>('api/v1/demoforecast/advanced-search', 'GET', null, { filter, page });
};

export const useAdvancedSearchQuery = (filter: SearchFilter, page: number) => {
    return useQuery({
        queryKey: ['DemoForecastController', 'AdvancedSearch', filter, page],
        queryFn: () => advancedSearchRequest(filter, page),
    });
};

export const createRequest = async (dto: CreateForecastDto) => {
    return await apiRequest<DemoForecast>('api/v1/demoforecast', 'POST', dto, null);
};

export const useCreateMutation = () => {
    return useMutation({
        mutationFn: (dto: CreateForecastDto) => createRequest(dto),
    });
};

export const updateRequest = async (id: number, dto: CreateForecastDto) => {
    return await apiRequest<DemoForecast>(`api/v1/demoforecast/${id}`, 'PUT', dto, null);
};

export const useUpdateMutation = () => {
    return useMutation({
        mutationFn: ({ id, dto }: { id: number; dto: CreateForecastDto }) => updateRequest(id, dto),
    });
};

export const uploadReportRequest = async (dto: UploadReportDto) => {
    return await apiRequest<string>('api/v1/demoforecast/upload-report', 'POST', serializeToFormData(dto), null);
};

export const useUploadReportMutation = () => {
    return useMutation({
        mutationFn: (dto: UploadReportDto) => uploadReportRequest(dto),
    });
};

