// Auto-generated by SharpSync
import { z } from 'zod';

export interface CreateForecastDto {
    date: string;
    temperatureC: number;
    summary: string;
}

export const CreateForecastDtoSchema = z.object({
    date: z.string().datetime().min(1),
    temperatureC: z.number().int().min(-100).max(100),
    summary: z.string().max(50).min(3),
});

export const CreateForecastDtoMetadata = {
    date: { required: true },
    temperatureC: { range: { min: -100, max: 100 } },
    summary: { maxLength: 50, minLength: 3 }
};
