// Auto-generated by SharpSync
import { z } from 'zod';

export interface DemoForecast {
    date: string;
    temperatureC: number;
    temperatureF: number;
    summary: string;
}

export const DemoForecastSchema = z.object({
    date: z.string().datetime(),
    temperatureC: z.number().int(),
    temperatureF: z.number().int(),
    summary: z.string(),
});
