// Auto-generated by SharpSync
import { useQuery, useMutation } from '@tanstack/react-query';
import { apiRequest } from './apiClient'; // Ensure you have an apiClient.ts exporting an apiRequest function.

export interface DemoForecast {
    date: string;
    temperatureC: number;
    temperatureF: number;
    summary: string;
}

export interface SearchFilter {
    term: string;
    minTemperature: number;
    includeHistorical: boolean;
}

export const getRequest = async () => {
    return await apiRequest<DemoForecast[]>('api/v1/demoforecast/all', 'GET', null, null);
};

export const useGetQuery = () => {
    return useQuery({
        queryKey: ['DemoForecastController', 'Get'],
        queryFn: () => getRequest(),
    });
};

export const getByIdRequest = async (id: number) => {
    return await apiRequest<DemoForecast>(`api/v1/demoforecast/${id}`, 'GET', null, null);
};

export const useGetByIdQuery = (id: number) => {
    return useQuery({
        queryKey: ['DemoForecastController', 'GetById', id],
        queryFn: () => getByIdRequest(id),
    });
};

export const getStatsRequest = async () => {
    return await apiRequest<string>('global-stats', 'GET', null, null);
};

export const useGetStatsQuery = () => {
    return useQuery({
        queryKey: ['DemoForecastController', 'GetStats'],
        queryFn: () => getStatsRequest(),
    });
};

export const searchRequest = async (q: string, minTemp: number) => {
    return await apiRequest<DemoForecast[]>('api/v1/demoforecast/search', 'GET', null, { q, minTemp });
};

export const useSearchQuery = (q: string, minTemp: number) => {
    return useQuery({
        queryKey: ['DemoForecastController', 'Search', q, minTemp],
        queryFn: () => searchRequest(q, minTemp),
    });
};

export const advancedSearchRequest = async (filter: SearchFilter, page: number) => {
    return await apiRequest<DemoForecast[]>('api/v1/demoforecast/advanced-search', 'GET', null, { page, ...filter });
};

export const useAdvancedSearchQuery = (filter: SearchFilter, page: number) => {
    return useQuery({
        queryKey: ['DemoForecastController', 'AdvancedSearch', filter, page],
        queryFn: () => advancedSearchRequest(filter, page),
    });
};

